version: "3.9"

services:
  binar-api:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: jarvis-iot:latest
    container_name: jarvis-iot
    networks:
      - net-gateway
    ports:
      - 5005:5000
    volumes:
      - /home/superman/dockerVolume/binarAPI/migrations:/app/migrations:rw
    environment:
      - APP_NAME=BinarAPI
networks:
  net-gateway:
    external: true