version: "3.9"

services:
  binar-api:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: binar-api:latest
    container_name: binar-api
    networks:
      - net-gateway
    ports:
      - 5001:5000
    volumes:
      - /home/superman/dockerVolume/binarAPI/files:/app/data/files:rw
      - /home/superman/dockerVolume/binarAPI/migrations:/app/migrations:rw
    environment:
      - APP_NAME=BinarAPI
networks:
  net-gateway:
    external: true